#!/usr/bin/env zsh

if [[ -z $STOW_FOLDERS ]]; then 
	STOW_FOLDERS="i3,kitty,nitrogen,polybar,rofi"
fi

if [[ -z $DOTFILES ]]; then 
	DOTFILES=$HOME/.dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/init
